---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  - dapper e2e-test
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/local-path-provisioner"
    tag: "${DRONE_BRANCH}-head-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - push

- name: docker-tagged-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/local-path-provisioner"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
#  - dapper e2e-test
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/local-path-provisioner"
    tag: "${DRONE_BRANCH}-head-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - push

- name: docker-tagged-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/local-path-provisioner"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

# Hack needed for s390x: https://gist.github.com/colstrom/c2f359f72658aaabb44150ac20b16d7c#gistcomment-3858388
node:
  arch: s390x

steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: rancher/drone-images:github-release-s390x
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-s390x.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

- name: docker-publish
  image: rancher/drone-images:docker-s390x
  volumes:
    - name: docker
      path: /var/run/docker.sock
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/local-path-provisioner"
    tag: "${DRONE_BRANCH}-head-s390x"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - push

- name: docker-tagged-publish
  image: rancher/drone-images:docker-s390x
  volumes:
    - name: docker
      path: /var/run/docker.sock
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/local-path-provisioner"
    tag: "${DRONE_TAG}-s390x"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
    target: "rancher/local-path-provisioner:${DRONE_BRANCH}-head"
    template: "rancher/local-path-provisioner:${DRONE_BRANCH}-head-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - push

- name: manifest-tag
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
    target: "rancher/local-path-provisioner:${DRONE_TAG}"
    template: "rancher/local-path-provisioner:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag

depends_on:
- amd64
- arm64
- s390x
