{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
{{- end }}
