FROM golang:1.23.1-alpine AS builder

COPY main.go /main.go
COPY go.mod /go.mod

RUN cd / && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-extldflags -static -s -w" -o /manager && \
    chmod 777 /manager

FROM scratch

COPY --from=builder /manager /manager

ENTRYPOINT [ "/manager" ]
