{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "local-path-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "local-path-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
