{{- $storageClasses := list }}
{{ if .Values.storageClassConfigs }}
{{ $storageClasses = .Values.storageClassConfigs }}
{{- else }}
{{ $storageClasses = dict .Values.storageClass.name .Values }}
{{ end }}
{{- $dot := . }}
{{- range $name, $values := $storageClasses }}
{{ if $values.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $name }}
  labels:
{{ include "local-path-provisioner.labels" $dot | indent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ $values.storageClass.defaultClass }}"
    defaultVolumeType: "{{ $values.storageClass.defaultVolumeType }}"
    {{- with $values.storageClass.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: {{ template "local-path-provisioner.provisionerName" $dot }}
volumeBindingMode: {{ $values.storageClass.volumeBindingMode }}
reclaimPolicy: {{ $values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
{{- if $values.storageClass.allowedTopologies }}
allowedTopologies:
{{ toYaml $values.storageClass.allowedTopologies | indent 0 }}
{{- end }}
{{- if or $values.storageClass.pathPattern $values.storageClass.userPattern $values.storageClass.groupPattern $values.storageClass.permPattern }}
parameters:
  {{- if $values.storageClass.pathPattern }}
  pathPattern: {{ $values.storageClass.pathPattern | quote }}
  {{- end }}
  {{- if $values.storageClass.userPattern }}
  userPattern: {{ $values.storageClass.userPattern | quote }}
  {{- end }}
  {{- if $values.storageClass.groupPattern }}
  groupPattern: {{ $values.storageClass.groupPattern | quote }}
  {{- end }}
  {{- if $values.storageClass.permPattern }}
  permPattern: {{ $values.storageClass.permPattern | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
