apiVersion: v1
kind: Pod
metadata:
  name: helper-pod
spec:
  containers:
  - name: helper-pod
    image: rancher/local-path-quota-helper:v0.0.34
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - name: quota-projects
      mountPath: /etc/projects
    - name: quota-projid
      mountPath: /etc/projid
    - name: device-dir
      mountPath: /dev
    - name: lock-dir
      mountPath: /var/lock
  volumes:
  - name: quota-projects
    hostPath:
      path: /etc/projects
      type: FileOrCreate
  - name: quota-projid
    hostPath:
      path: /etc/projid
      type: FileOrCreate
  - name: device-dir
    hostPath:
      path: /dev
  - name: lock-dir
    hostPath:
      path: /var/lock
      type: DirectoryOrCreate
