kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
      "nodePathMap":[{
        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
        "paths":["/tank/"]
      }]
    }
  setup: |-
    #!/bin/sh
    zfs create -o quota=${VOL_SIZE_BYTES} ${VOL_DIR:1}
    chmod g+w ${VOL_DIR}
    chmod o+w ${VOL_DIR}
  teardown: |-
    #!/bin/sh
    zfs destroy ${VOL_DIR:1}
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: srueg/zfs-utils
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tank
          name: data
          mountPropagation: Bidirectional
