apiVersion: v1
kind: Pod
metadata:
  name: helper-pod
spec:
  containers:
  - name: helper-pod
    image: xxx/storage-xfs-quota:v0.1
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - name: xfs-quota-projects
      subPath: projects
      mountPath: /etc/projects
    - name: xfs-quota-projects
      subPath: projid
      mountPath: /etc/projid
    - name: device-dir
      mountPath: /dev
  volumes:
  - name: xfs-quota-projects
    hostPath:
      path: /etc/projects
      type: FileOrCreate
  - name: xfs-quota-projid
    hostPath:
      path: /etc/projid
      type: FileOrCreate
  - name: device-dir
    hostPath:
      path: /dev
