apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../deploy

configMapGenerator:
- name: local-path-config
  namespace: local-path-storage
  behavior: merge
  files:
  - helperPod.yaml
  - setup
  - teardown

generatorOptions:
  disableNameSuffixHash: true
