#!/bin/sh

while getopts "m:s:p:" opt
do
    case $opt in
        p)
        absolutePath=$OPTARG
        ;;
        s)
        sizeInBytes=$OPTARG
        ;;
        m)
        volMode=$OPTARG
        ;;
    esac
done

xfsPath=$(dirname "$absolutePath")
pvcName=$(basename "$absolutePath")

# support xfs quota
type=`stat -f -c %T ${xfsPath}`
if [ ${type} == 'xfs' ]; then

    echo "support xfs quota"
    xfs_quota -x -c "limit -p bhard=0 ${pvcName}" ${xfsPath}
fi

rm -rf ${absolutePath}
if [ ${type} == 'xfs' ]; then
    echo "$(sed "/${pvcName}/d" /etc/projects)" >  /etc/projects
    echo "$(sed "/${pvcName}/d" /etc/projid)" >  /etc/projid
    xfs_quota -x -c "report -pbih" ${xfsPath}
fi

