apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-xfs-quota
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  quotaEnforcement: xfs
