apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-folder-pvc
  annotations:
    "rancher.io/customFolderName": "demo1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
