apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /nginx
      subPath: nginx
    ports:
    - containerPort: 80
  - name: volume-test-2
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "1000000"
    volumeMounts:
    - name: volv
      mountPath: /busybox
      subPath: busybox
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
