#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/local-path-provisioner dist/artifacts/local-path-provisioner${SUFFIX}

IMAGE=${REPO}/local-path-provisioner:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

if [ "$ARCH" = "riscv64" ]; then
    export DOCKER_BUILDKIT=1
    DOCKER_ARGS="--platform=$ARCH --build-arg=BASE=riscv64/alpine:edge"
fi
docker build ${DOCKER_ARGS} -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

echo ${IMAGE} > ./bin/latest_image
