apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capacity-budget-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
