name: Scan With Trivy and Upload Results to GitHub Security Tab

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*
  pull_request:

jobs:
  scan-vulnerabilities:
    name: Scan for Vulnerabilities With Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy Scan Results to GitHub Security Tab
        if: failure()
        uses: github/codeql-action/upload-sarif@d1ba80a13dd99fba24a470575428917156a28b43 # v4
        with:
          sarif_file: "trivy-results.sarif"
